List<String> messages = [
  "Képes vagy rá!",
  "Csak te és én :)",
  "Nyugodj meg, attól megnyugszol",
  "Kezd összeállni :)",
  "A legjobb vagy! ;)",
  "Little pig, little pig, let in me!",
  "Say my name! ",
  "Ahol árnyék van, ott fény is!",
  "NEM VAGYOK BUZI!!",
  "Sötétbe is fényes vagy",
  "Never gonna give you up",
  "Én Svájc vagyok",
  "Nekem lehet jó!",
  "Mesélek a bornak",
  "Meséld el mégegyszer",
  "Sweet Caroline",
  "Good times never seem so good",
  "Ember most jövök ki a templomból",
  "NA én veled nem játszok!!",
  "Kell egy kis bulika! :D",
  "VAN EGY SZÁL CIGID?",
  "Nyugi! :)",
  "Aki nem bírja minek iszik? Igaaz Máté?",
  "Ha ideges vagy, csak nyugodj le.",
  "Holnap én már nem jövök be",
  "Go Haza",
  "Holnaptól táppénzen vok cs",
  "Holnaptól igazolatlan",
  "Így van"
];
